name: Generate VAPID keys

on:
  workflow_dispatch:

jobs:
  vapid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npx web-push generate-vapid-keys
